taskDefinition: 'organizer-db'
cluster: 'dev'
count: 1
enableECSManagedTags: False
enableExecuteCommand: False
launchType: 'FARGATE'
networkConfiguration:
  awsvpcConfiguration:
    subnets:
      - '<SUBNET>'
    assignPublicIp: 'ENABLED'
tags: 
  - key: 'app'
    value: 'organizer'