- file_system_name: 'organizer-sql-creds'
  mount_target:
      subnet_id: '<DB_SUBNET>'
- file_system_name: 'organizer-sql-scripts'
  mount_target:
      subnet_id: '<DB_SUBNET>'
- file_system_name: 'organizer-sql-data'
  mount_target:
      subnet_id: '<DB_SUBNET>'