taskDefinition: 'organizer-backend'
cluster: 'dev'
count: 1
enableECSManagedTags: False
enableExecuteCommand: False
launchType: 'FARGATE'
networkConfiguration:
  awsvpcConfiguration:
    subnets:
      - '<SUBNET>' # public subnet
    securityGroups:
      - '<SECURITY_GROUP>'
    assignPublicIp: 'DISABLED'
tags: 
  - key: 'app'
    value: 'organizer'